### ISSUE TITLE
Backend Routes 

### ISSUE THREAD

**Issue by mashuDuek** [youthinkasido/darebnb#1]
1. What do you mean by this: `API endpoints refer to the location of an object or objects, in our case, a spot or spots.`

API stands for Application Program Interface. It means that the endpoints that our project has is how the outside world will interface with our project. Each endpoint should expose a particular set of data. 

2. `GET /api/spots` this one can be a little tricky, because we should send spots up based on map filters (meaning the bounds of the map), as well as based on a users bookings. We could do something like `GET /api/users/:user_id/spots`, and that should hit `SpotsController#index` - and have a custom route for the spots that should be returned based on the map, maybe something like `GET /api/spots/map_filters`, that should hit `SpotsController#map_filters`. Or we could totally do `GET /api/users/:user_id/spots` and `GET /api/spots` (and this one would take in map filters as params) both would hit index controller action, and then in that action you could check if you were given a `:user_id` do one thing, if not you should accept map bounds. Lmk if you have questions on this. 

3. Reviews should be able to be edited and deleted. 

4. We need to have bookings here. I need to be able to book a place to make a complete airBnb clone.

**Comment by youthinkasido** [comment]
- Added routes to create or delete bookings
- Added routes to edit or delete reviews
- Edited route to return booked spots for a given user 
- Added route to return spots based on map filters passed through params 

I am a bit confused on the map filters portion on exactly how to implement the routes.
