### ISSUE TITLE
Frontend Routes 

### ISSUE THREAD

**Issue by mashuDuek** [youthinkasido/darebnb#2]
I like it, but it needs to be more thorough. 
What is rendered at `/`? 
Inside of SpotsIndex component, you probably want SpotIndexItem (or SpotIndexThumbnail) or something of the sort. 

Try to format this more like BlueBird wiki has their frontend routes.

**Comment by youthinkasido** [comment]
- updated ' / ' to point to splash page.
- Added Component tree.
- Reformatted text to emulate BlueBird wiki.

Are there additional routes you could suggest in order to make it more thorough?
